[package]
name = "w3"
version = "0.0.0"
authors = ["Jay Krell <jay.krell@cornell.edu>"]
edition = "2018"

[dependencies]

[build-dependencies]
cc = "1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
